config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
        root "dashboards#show", as: :dashboard
  end

  root to: "homes#show"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :messages, only: [:new, :create]
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :receiver_id

  validates :phone, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    account_sid = ENV["ACCOUNT_SID"]
    auth_token = ENV["AUTH_TOKEN"]

    @client = Twilio::REST::Client.new account_sid, auth_token

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @user = User.new
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @receiver = User.find_by(phone: params[:message][:receiver])
    @message = Message.create(message_params.merge(receiver: @receiver))
    account_sid = ENV["ACCOUNT_SID"]
    auth_token = ENV["AUTH_TOKEN"]

    # set up a client to talk to the Twilio REST API
    @client = Twilio::REST::Client.new account_sid, auth_token

    @client.account.messages.create({
      from: current_user.phone,
      to: "#{params[:message][:receiver]}",
      body: params[:message][:body]
    })

    redirect_to root_path
  end

  private

  def message_params
    params.
      require(:message).
      permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:phone, :password)
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  def send_sms
    message = params[:message]
    number = params[:number]
    account_sid = ENV["ACCOUNT_SID"]
    auth_token = ENV["AUTH_TOKEN"]

    @client = Twilio::REST::Client.new account_sid, auth_token

    @message = @client.account.messages.create({:to => "+1"+"#{number}",
                                                :from => "+18622033911",
                                                :body => "#{message}"})
    redirect_to dashboard_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :phone, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/views/dashboards/show.html.erb
<h4>Welcome <%= current_user.email %>
<<<<<<< HEAD
  <div>
    <%= link_to "New Message", new_message_path %>
  </div>
  <div>
    <% @client.account.messages.list({ }).each do |message| %>
      <%= puts message.body %>
    <%end%>
  </div>
=======
>>>>>>> 11206efec7196b739f6d18ad7db0ce58116ddc05

app/views/homes/show.html.erb
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.phone_field :phone, placeholder: "Phone Number" %>
  </div>
  <div>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>


<%= form_for @user do |form| %>
  <div>
    <%= form.email_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= form.phone_field :phone, placeholder: "Phone Number" %>
  <div>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Textr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <% if signed_in? %>
    Welcome <%= current_user.email %> <%=link_to "Sign out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_session_path %>
    <%= link_to "Sign up", new_user_path %>
  <% end %>
  <body>

    <%= yield %>

  </body>
</html>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= form_for @message do |form| %>
  <%= form.phone_field :receiver, placeholder: "type number" %><br />
  <%= form.text_area :body, placeholder: "type message here" %><br />
  <%= form.submit "Send Message" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.email_field :email, placeholder: "Email" %>
  </div>
  <div>
<<<<<<< HEAD
    <%= form.phone_field :phone, placeholder: "Phone Number" %>
=======
    <%= form.telephone_field :phone, placeholder: "Phone" %>
>>>>>>> 11206efec7196b739f6d18ad7db0ce58116ddc05
  <div>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>